Repository Justsvetoslavov/Object-oriented_programming_FMI, pull requests merged in 2023-03, with the labels that each got.

#66 Pract.02: Add 01-03 | Kiril Georgiev
  Seminars/Sem.02/Pract.02/Task01.cpp
  Seminars/Sem.02/Pract.02/Task02.cpp
  Seminars/Sem.02/Pract.02/Task03.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#72 Pract.02 Add 04-07 Natalia Nakollofski
  Seminars/Sem.02/Pract.02/Task 04.cpp
  Seminars/Sem.02/Pract.02/Task 06.cpp
  Seminars/Sem.02/Pract.02/Task 07.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#83 Pract.02: Add 01 | Igor Simeonov
  Seminars/Sem.02/Pract.02/Task01.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#78 Pract.02: Add 04-06 | Raya Grigorova
  Seminars/Sem.02/Pract.02/Task04.cpp
  Seminars/Sem.02/Pract.02/Task06.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#111 Pract.03 Add Docx Fix for Task01
  Seminars/Sem.03/Pract.03/README.md
Labels: 🆗 state: Approved, 📜 type: Documentation

#110 Pract.03: Add 01-02 | Vasil Paligorov
  Seminars/Sem.03/Pract.03/Task01.cpp
  Seminars/Sem.03/Pract.03/Task02.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#98 Pract.02: Add 07 | Ivan Stoynev
  Seminars/Sem.02/Pract.02/Task07.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#79 Pract.02: Add 07-08 | Raya Grigorova
  Seminars/Sem.02/Pract.02/Task07.cpp
  Seminars/Sem.02/Pract.02/Task08.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#120 Pract.03: Add 01 | Radoslav Angelov
  Seminars/Sem.03/Pract.03/Task1.cpp
  Seminars/Sem.03/Pract.03/data.csv
Labels: 🆗 state: Approved, 💻 type: Solutions

#124 Pract.03: Add 01 | Boyan Vidolov
  Seminars/Sem.03/Pract.03/Task01.cpp
Labels: 💻 type: Solutions

#129 Pract.04: Add 04 | Yonko Draganov
  Seminars/Sem.04/Pract.04/Task04/OOP_Pract.cpp
  Seminars/Sem.04/Pract.04/Task04/Secret.cpp
  Seminars/Sem.04/Pract.04/Task04/Secret.h
Labels: 🆗 state: Approved, 💻 type: Solutions

#116 Pract.03: Add 01 | Yonko Draganov
  Seminars/Sem.03/Pract.03/Task01.cpp
Labels: 🆗 state: Approved, 💻 type: Solutions

#139 Update Sem.05 ReadMe
  Seminars/Sem.05/README.md
Labels: 📜 type: Documentation

#130 Pract.04: Added Task02 | Boyan Vidolov
  Seminars/Sem.04/Pract.04/Task02.cpp
  Seminars/Sem.04/Pract.04/Task02/Exam.cpp
  Seminars/Sem.04/Pract.04/Task02/Exam.h
  Seminars/Sem.04/Pract.04/Task02/Task.cpp
  Seminars/Sem.04/Pract.04/Task02/Task.h
Labels: 🚧 state: Changes requested, 💻 type: Solutions
